### ISSUE TITLE
[Question] Best practice for passing back information from ViewController to Presenter

### ISSUE THREAD

**Issue by shaneowens** [outware/om-viper#5]
In `ToDoDetailPresenter.m`

We have

`- (void)dataAvailable:(ToDoDetailPresentationModel *)item`

```
{
    ToDoDetailViewModel *viewModel = [[ToDoDetailViewModel alloc] init];
    viewModel.title = item.title;
    viewModel.content = item.content;

    [self.userInterface displayItem:viewModel];
}
```

Which is a nice clean way to pass information to 

`ToDoDetailViewController.m`

And update the view

```
- (void)displayItem:(ToDoDetailViewModel *)item {
  self.viewModel = item;
}

- (void)setViewModel:(ToDoDetailViewModel *)viewModel {
  _viewModel = viewModel;

  self.title = viewModel.title;
  self.textView.text = viewModel.content;
}
```

However, I was wondering what is the best way to pass information back from `ToDoDetailViewController` to `ToDoDetailPresenter` if a property of the `viewModel` is edited

_e.g._ `viewModel.content`

Should there be

**a)** an update method with a viewModel
_e.g._ `update:(ToDoDetailViewModel*)viewModel`

or 

**b)** an update method with a string
_e.g._ `updateContent:(NSString *)content`

Is there a best practice, and if so why?

Many Thanks for posting this sample application.

**Comment by jeanetienne** [comment]
I don't think there's a strong best practice. I believe this comes down to the details of a project and as usual I'd suggest to find what works best for your team/project and then stay consistent throughout the project.

My personal opinion would be that the view should consume viewModels but not keep references to them, I believe the view should deal with standard types provided by the UI framework, and should return those types back to the Presenter. Then I'd say it's the Presenter's job to figure out where this pice of data belongs, which ViewModel it should change. So personally I'd go with `updateContent:(NSString *)content`, or even better following UIKit flavours, something along the lines of `contentDidUpdateWithText:(NSString *)newContent`.

But I'm sure @bjornjuwenho may have a different opinion and good arguments to support it as well ;)

**Comment by shaneowens** [comment]
Thanks for your reply @jeanetienne.

Could you clarify what you mean by -

> My personal opinion would be that the view should consume viewModels but not keep references to them

as in the `ToDoDetailViewController` example is has a `ToDoDetailViewModel` property.

```
//
//  ToDoDetailViewController.m
//  OutwareToDoObjc
//
//  Created by Bjorn Juwen Ho on 23/12/2014.
//  Copyright (c) 2014 Bjorn Juwen Ho. All rights reserved.
//

#import "ToDoDetailViewController.h"
#import "ToDoDetailViewModel.h"

@interface ToDoDetailViewController ()
@property(nonatomic, strong) ToDoDetailViewModel *viewModel;
@end
```

Many Thanks,
Shane

**Comment by jeanetienne** [comment]
Sorry for the late reply.

You're right, here the `ToDoDetailViewController` has a reference to `ToDoDetailViewModel`.
My personal opinion and experience make me think we could do without this property, but on the other hand it is not very harmful. I can't remember exactly why we chose to do this on this sample project.

As I said, this is where we're getting into the tiny details and best practices. You should do what makes more sense to you/your team, stay consistent with this choice for a whole project, and then see if it worked/how it could be improved.

**Comment by shaneowens** [comment]
Cheers @jeanetienne - much appreciated.
